apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
      - name: python-container
        image: acrdevgitops2026.azurecr.io/gitops-app:v1