apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
      - name: python-container
        image: acrdevgitops2026.azurecr.io/gitops-app:b81e60c7a0070e33fa21ee6a0f4f68727ddde79e